# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# æ·»åŠ æ–°èœå•é¡¹éµå¾ªä»¥ä¸‹è§„åˆ™
# menu:
#  link:               fontawesomeå›¾æ ‡ï¼Œçœç•¥å‰ç¼€ï¼Œæœ¬ä¸»é¢˜å‰ç¼€ä¸º icon-ï¼Œå¿…é¡»
#    text: About       èœå•æ˜¾ç¤ºçš„æ–‡å­—ï¼Œå¦‚æœçœç•¥å³é»˜è®¤ä¸å›¾æ ‡ä¸€è‡´ï¼Œé¦–å­—æ¯ä¼šè½¬å¤§å†™
#    url: /about       é“¾æ¥ï¼Œç»å¯¹æˆ–ç›¸å¯¹è·¯å¾„ï¼Œå¿…é¡»ã€‚
#    target: _blank    æ˜¯å¦è·³å‡ºï¼Œçœç•¥åˆ™åœ¨å½“å‰é¡µé¢æ‰“å¼€
menu:
  home:
    text: ä¸»é¡µ
    url: /
  archives:
    text: æ•™ç¨‹å½’æ¡£
    url: /archives
  tags:
    text: æ•™ç¨‹æ ‡ç­¾
    url: /tags
  th-list:
    text: æ•™ç¨‹åˆ†ç±»
    url: /categories
  link:
    text: æ•™ç¨‹ä»“åº“
    url: http://t.cn/EVUeCdA

# ä½ çš„å¤´åƒurl
avatar: /img/avatar.jpg
# avatar link
avatar_link: /
# å¤´åƒèƒŒæ™¯å›¾
brand: /img/brand.jpg
# favicon
favicon: /favicon.ico

# email
email: 1398371419@qq.com

# è®¾ç½® Android L Chrome æµè§ˆå™¨çŠ¶æ€æ é¢œè‰²
color: '#3F51B5'

# é¡µé¢æ ‡é¢˜
tags_title: æ ‡ç­¾
archives_title: å½’æ¡£
categories_title: åˆ†ç±»

# æ–‡ç« æˆªæ–­
excerpt_render: true
excerpt_length: 200
excerpt_link: é˜…è¯»å…¨æ–‡...
mathjax: false
archive_yearly: true

# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æœ€åæ›´æ–°æ—¶é—´
show_last_updated: true

# æ˜¯å¦å¼€å¯åˆ†äº«
share: true

# æ˜¯å¦å¼€å¯æ‰“èµï¼Œå…³é—­ reward: false
reward: false

# æ˜¯å¦å¼€å¯æœç´¢
search: true

# æ˜¯å¦å¤§å±å¹•ä¸‹æ–‡ç« é¡µéšè—å¯¼èˆª
hideMenu: true

# æ˜¯å¦å¼€å¯toc
# toc: false
toc:
  list_number: true  # æ˜¯å¦æ˜¾ç¤ºæ•°å­—æ’åº

# æ–‡ç« é¡µç•™è¨€å†…å®¹ï¼Œhexoä¸­æ‰€æœ‰å˜é‡åŠè¾…åŠ©å‡½æ•°ç­‰å‡å¯è°ƒç”¨ï¼Œå…·ä½“è¯·æŸ¥é˜… hexo.io
postMessage: ğŸ”¥ğŸ”¥ğŸ”¥ å»<a href="http://t.cn/EVUeCdA">æ•™ç¨‹ä»“åº“</a>è·å–æ›´å¤šè¶…å€¼æ•™ç¨‹ï¼ğŸ”¥ğŸ”¥ğŸ”¥<br>ğŸ‘‰ğŸ‘‰ğŸ‘‰ äº²~è´­ä¹°ä¹‹å‰è®°å¾—ç‚¹å‡»æ•™ç¨‹é¢„è§ˆï¼Œä»¥é˜²è´­ä¹°é”™è¯¯å“¦ï¼</br>

# ç«™é•¿ç»Ÿè®¡ï¼Œå¦‚è¦å¼€å¯ï¼Œè¾“å…¥CNZZç«™ç‚¹idï¼Œå¦‚ cnzz: 1255152447
cnzz: false

# ç™¾åº¦ç»Ÿè®¡ï¼Œå¦‚è¦å¼€å¯ï¼Œæ”¹ä¸ºä½ çš„ key
baidu_tongji: false

# è…¾è®¯åˆ†æï¼Œå¦‚è¦å¼€å¯ï¼Œè¾“å…¥ç«™ç‚¹id
tajs: false

# google
google_analytics: false
google_site_verification: false

# sogouç«™é•¿éªŒè¯ http://zhanzhang.sogou.com/
sogou_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# ä»¥ä¸‹è¯„è®ºæ’ä»¶å¼€å¯ä¸€ä¸ªå³å¯
# æ˜¯å¦å¼€å¯ disqus
disqus_shortname: false
# æ˜¯å¦å¼€å¯å‹è¨€è¯„è®º, å¡«å†™å‹è¨€ç”¨æˆ·id
uyan_uid: false
# æ˜¯å¦ä½¿ç”¨ gitmentï¼Œhttps://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# use gitalk://github.com/gitalk/gitalk
gitalk: false
#  owner:
#  repo:
#  client_id:
#  client_secret:

# Valine Comment system. https://valine.js.org
valine:
  enable: false # å¦‚æœä½ æƒ³ä½¿ç”¨valineï¼Œè¯·å°†å€¼è®¾ç½®ä¸º true
  appId:  # your leancloud appId
  appKey:  # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Just go go # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# æ˜¯å¦å¼€å¯Hyper Commentsï¼Œå¡«å†™idåˆ™å¯ç”¨ï¼Œfalseåˆ™ç¦ç”¨ã€‚http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false


# è§„èŒƒç½‘å€
# è®©æœç´¢å¼•æ“é‡å®šå‘ä½ çš„ä¸åŒåŸŸåã€ä¸åŒå­åŸŸã€åŒåŸŸä¸åŒç›®å½•çš„ç«™ç‚¹åˆ°ä½ æœŸæœ›çš„è·¯å¾„
# https://support.google.com/webmasters/answer/139066
# å‡è®¾é…ç½®ä¸º canonical: http://imys.netï¼Œé‚£ä¹ˆä»æœç´¢å¼•æ“ä¸­ www.imys.net è¿›å…¥ä¼šé‡å®šå‘åˆ° imys.net
canonical: false

# ç‰ˆæƒèµ·å§‹å¹´ä»½
since_year: 2018

# ç”¨æˆ·é¡µé¢ä¸­ä½œè€…ç›¸å…³çš„æè¿°æ€§æ–‡å­—ï¼Œå¦‚ä¸éœ€è¦è®¾ä¸º false
about: ç”¨æˆ·é¡µé¢ä¸­ä½œè€…ç›¸å…³çš„æè¿°æ€§æ–‡å­—ï¼Œå¦‚ä¸éœ€è¦è®¾ä¸º false

# â€œä¸è’œå­â€è®¿é—®é‡ç»Ÿè®¡ï¼Œè¯¦è§ http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: ç«™ç‚¹æ€»è®¿å®¢æ•°ï¼š
  site_pv: ç«™ç‚¹æ€»è®¿é—®é‡ï¼š

# åŠ¨æ€å®šä¹‰title
title_change:
  normal: (ã¤ã‚§âŠ‚)å’¦!åˆå¥½äº†!
  leave: æ­»é¬¼å»å“ªé‡Œäº†ï¼

# è®¾ç½®ä¸º true å‘å¸ƒåå°†ä½¿ç”¨ unpkg cdn æœ€æ–°çš„ä¸»é¢˜æ ·å¼
# å¦‚æœæƒ³è®©ä½ çš„è‡ªå®šä¹‰æ ·å¼ç”Ÿæ•ˆï¼ŒæŠŠæ­¤é¡¹è®¾ä¸º false
cdn: true

# è®¾ç½®ä¸º true å°†ä½¿ç”¨ lightbox render å›¾ç‰‡
lightbox: true

# icpå¤‡æ¡ˆå·  ICP_license: äº¬ICPå¤‡1234556å·-1
ICP_license: false
